name: Google Cloud Run Deploy (Front-end)
# https://github.com/google-github-actions/setup-gcloud
on:
    push:
        branches:
            - main
        paths:
            - "client/**"

env:
    PROJECT_ID: ${{ secrets.GCR_PROJECT }}
    RUN_REGION: us-east1
    SERVICE_NAME: clove-book

jobs:
    build:
        name: Build React App
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@main

            - name: Setup Node.js (NPM)
              uses: actions/setup-node@master
              with:
                  node-version: "16.X"

            - name: Use cached node_modules
              uses: actions/cache@master
              with:
                  path: client/node_modules
                  key: nodeModules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      nodeModules-

            - name: Install dependencies
              run: yarn install --frozen-lockfile
              working-directory: client
              env:
                  CI: true

            - name: Build Development
              run: yarn build
              working-directory: client

            - name: Archive Production Artifact
              uses: actions/upload-artifact@main
              with:
                  name: build
                  path: client/build

    deploy-gcr:
        name: Deploy to GCR
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@main

            - name: Download Artifact
              uses: actions/download-artifact@main
              with:
                  name: build
                  path: .docker/build

            - name: Setup GCloud Auth
              id: auth
              uses: google-github-actions/auth@v0.4.0
              with:
                  credentials_json: ${{ secrets.GCR_SA_KEY }}

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v0.2.1

            # Build and push image to Google Container Registry
            - name: Build & Push
              run: |-
                  gcloud builds submit \
                    --quiet \
                    --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
              working-directory: .docker

            # Deploy image to Cloud Run
            - name: Deploy GCR
              run: |-
                  gcloud run deploy "$SERVICE_NAME" \
                    --quiet \
                    --region "$RUN_REGION" \
                    --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
                    --platform "managed" \
                    --allow-unauthenticated
