name: Go

on:
  push:
    branches: [ main ]
    paths: "server/**"

env:
  PROJECT_ID: 'clovebook'
  RUN_REGION: us-east1
  SERVICE_NAME: clove-book-server
  USERNAME: 'accrazed'
  IMG_NAME: 'CLOVEBOOK_SERVER'
  REGISTRY: 'gcr.io'
  BUILDER: 'paketobuildpacks/builder:base'
  
jobs:
  build:
    name: Build Go App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set App Name
      run: 'echo "IMG_NAME=$(echo ${REGISTRY})/$(echo ${USERNAME})/$(echo ${IMG_NAME})" >> $GITHUB_ENV'
    - id: login
      uses: docker/login-action@v1
      with:
        username: ${{ env.USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        registry: ${{ env.REGISTRY }}
    
    - name: Pack Remote Build
      uses: dfreilich/pack-action@v2
      with:
        args: 'build ${{ env.IMG_NAME }} --builder ${{ env.BUILDER }} --publish'


