name: Push Server to GCR

on:
  workflow_dispatch:
    paths: "server/**"
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-east1
  USERNAME: "accrazed"
  SERVICE_NAME: "clove-book-server"
  REGISTRY: "gcr.io"
  BUILDER: "paketobuildpacks/builder:base"

jobs:
  build:
    name: Build+Upload Go App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Encode Key
        run: 'echo "GCR_SA_KEY_B64=$(echo ${{ secrets.GCR_SA_KEY }}) | base64" >> $GITHUB_ENV'

      - id: login
        uses: docker/login-action@v1
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCR_SA_KEY }}

      - name: Pack Remote Build
        uses: dfreilich/pack-action@v2.0.0
        with:
          args: "build ${{ env.SERVICE_NAME }} --path ./server --builder ${{ env.BUILDER }}"

      - name: Push to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${GCR_SA_KEY_B64}
          project_id: ${{ secrets.GCR_PROJECT }}
          image_name: ${SERVICE_NAME}
          image_tag: ${GITHUB_SHA}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1

      - name: Deploy Image
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "$REGISTRY/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
