name: Push Server to GCR

on:
  workflow_dispatch:
    paths: "server/**"
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-east1
  USERNAME: "accrazed"
  SERVICE_NAME: "clove-book-server"
  REGISTRY: "gcr.io"
  BUILDER: "paketobuildpacks/builder:base"

jobs:
  build:
    name: Build+Upload Go App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set App Name
        run: 'echo "IMG_NAME=$(echo ${REGISTRY})/$(echo ${PROJECT_ID})/$(echo ${SERVICE_NAME}:$(echo ${GITHUB_SHA}))" >> $GITHUB_ENV'

      - id: login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCR_SA_KEY }}

      - name: Pack Remote Build
        uses: dfreilich/pack-action@v2.0.0
        with:
          args: "build ${{ env.SERVICE_NAME }} --path ./server --builder ${{ env.BUILDER }} --publish"

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCR_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1

      - name: Deploy Image
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "$REGISTRY/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
