### Auth User

POST http://localhost:8000/users/auth HTTP/1.1
Content-Type: application/json

{
  "username": "accrazed",
  "email": "accrazed@gmail.com"
}

### Create User

POST http://localhost:8000/users?code=945831 HTTP/1.1
Content-Type: application/json

{
  "username": "accrazed",
  "email": "accrazed@gmail.com",
  "firstName": "Amelia",
  "lastName": "Castilla",
  "password": "123456789"
}

### Login User

GET http://localhost:8000/users/login?username=accrazed&password=123456789 HTTP/1.1

### Update User

PUT http://localhost:8000/users/623fce4643d2b1a22ae74415 HTTP/1.1
content-type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFjY3JhemVkIiwidXNlcklEIjoiNjIzZmNlNDY0M2QyYjFhMjJhZTc0NDE1IiwiZXhwIjoxNjQ4NDM1MjYzLCJpYXQiOjE2NDgzNDg4NjN9.biTCxhDP190ozJJJ7K1PoHyfFCxan-dOgmMwJJZCR0s; Path=/; Domain=clovebook.com; Max-Age=1648356063; HttpOnly; Secure

{
    "password": "123456789"
}

### Get User

GET http://localhost:8000/users/623fce4643d2b1a22ae74415 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFjY3JhemVkIiwidXNlcklEIjoiNjIzZmNlNDY0M2QyYjFhMjJhZTc0NDE1IiwiZXhwIjoxNjQ4NDM1MzcyLCJpYXQiOjE2NDgzNDg5NzJ9.j-Ane5yW9bsEumVrjCdGympGZLBFDKkU5IiUCGgWH0c; Path=/; Domain=clovebook.com; Max-Age=1648356172; HttpOnly; Secure

### Delete User

DELETE http://localhost:8000/users/623fce4643d2b1a22ae74415 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFjY3JhemVkIiwidXNlcklEIjoiNjIzYTgxM2JhM2ZlZTU3NmNkMDkxNTVlIiwiZXhwIjoxNjQ4MzEyMTA2LCJpYXQiOjE2NDgzMTE4MDZ9.5WxAszXEEyC9AH02Cn9D5kFKgGBeH8tRgiMuL4LXGz8; Path=/; Domain=clovebook.com; Max-Age=1648319006; HttpOnly; Secure

### Email Password Reset

POST http://localhost:8000/users/reset?email=accrazed@gmail.com HTTP/1.1

### Password Reset

PUT http://localhost:8000/users/reset?email=accrazed@gmail.com&password=potato&code=790451 HTTP/1.1


### SAMPLE
POST localhost:8000/users/login?username=accrazed&password=123456789 HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

